"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

fib1 = 1
fib2 = 2
fibSum = 0

while fib2 < (4 * 1000 * 1000):
    if fib2 % 2 == 0:
        fibSum += fib2

    tmpFib = fib1 + fib2
    fib1 = fib2
    fib2 = tmpFib

print str(fibSum)