"""
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
"""


pentagonalNumbers = []
isPentagonalNumbers = {}


for i in xrange(1, 10000):
    p = i * (3*i - 1) / 2
    pentagonalNumbers.append(p)
    isPentagonalNumbers[p] = True

for j in pentagonalNumbers:
    for k in pentagonalNumbers:
        if j <= k:
            break

        s = j + k
        d = j - k

        if s in isPentagonalNumbers and d in isPentagonalNumbers:
            print str(d)